### ISSUE TITLE
Why the fork?

### ISSUE THREAD

**Issue by omeid** [Chion82/react-native-web-extended#1]
I found about this repo through your amazing work in native-base-web, is there a reason this fork exists and why should I use this over react-native-web?

Cheers.

**Comment by neoman-titan** [comment]
I use it because I use the extended components which are very nice for prototyping native apps in my web browser :+1 Hopefully the stuff gets merged into the official repository some day.

**Comment by omeid** [comment]
Yeah, the extended components are nice, but wouldn't it be nice to actually merge them upstream? has there been issues in that regard?

I am concerned because I think a lot of useful work will be duplicated and this might make using react-base-web a hard choice, because obviously react-native-web has a lot more momentum and is backed by a big player, so it won't go anywhere anytime soon, or so one would hope ;)

**Comment by Chion82** [comment]
Yeah, I will create a pull request for the upstream some days later. Currently the extended APIs and components in this repo are so experimental and unstable for production. I think it's just too early by now. See [native-base-web issue #2](https://github.com/Chion82/native-base-web/issues/2)

**Comment by omeid** [comment]
Thanks for the very swfit response! I am sure the react-native-web people will work a way out to mark these APIs and/or components "experimental/beta", pushing them over at react-native-web will also means you get more feedback much faster! and if there are some changes that they're not welling to compormise, you can look into alternative early before developing too much with those assumptions.

Of course, you're free to do as you please, I am just making some suggestion because I think there is a lot of potential in native-base-web. And once again, thanks for making this great work opensource!

Cheers.
